# yaml-language-server: $schema=https://json.schemastore.org/pull-request-labeler.json

# docs: https://github.com/actions/labeler
---
docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/*'
          - '**/*.md'

iac:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.json'
          - '**/*.jsonc'
          - '**/*.bicep'
          - '**/*.bicepparam'
          - '**/*.ps1'
          - '**/*.psm1'
