# Platform Services
deploy_Platform:
  templateFile: ./src/orchestration/platform/platform.bicep
  templateParameterFile: ./src/configuration/platform/platform.bicepparam

## Canary
deploy_Platform_Canary:
  templateFile: ./src/orchestration/platform/platform.bicep
  templateParameterFile: ./src/configuration/platform/platform-canary.bicepparam

# Platform Landing Zone Subscriptions
## Connectivity
deploy_Platform_Connectivity:
  templateFile: ./src/orchestration/platformConnectivity/platformConnectivity-hub.bicep
  templateParameterFile: ./src/configuration/platform/platformConnectivity-hub.bicepparam

## Management
deploy_Platform_Management:
  templateFile: ./src/orchestration/platformManagement/platformManagement.bicep
  templateParameterFile: ./src/configuration/platform/platformManagement.bicepparam

