name: Copilot Agent Task
description: Create a well-structured task for GitHub Copilot Coding Agent to implement
title: "[Copilot Task]: "
labels: ["copilot-agent", "infrastructure"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 Copilot Coding Agent Task
        
        Use this template to create tasks that GitHub Copilot Coding Agent can implement autonomously.
        The more detail you provide, the better the results!
        
        **After submitting:** Assign this issue to `Copilot` to start autonomous implementation.

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Where is the code? What currently exists? Why is this change needed?
      placeholder: |
        The patient portal infrastructure in `infra/bicep/contoso-patient-portal/` 
        needs monitoring before production go-live. Currently there are no alert 
        rules configured.
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What specifically needs to be created or changed? Be detailed!
      placeholder: |
        **Create 4 alert rules:**
        1. CPU Alert: > 80% for 5 minutes
        2. Memory Alert: > 85% for 5 minutes
        3. HTTP 5xx Alert: > 10 errors in 5 minutes
        4. Response Time Alert: > 3 seconds average
        
        **Action Group:**
        - Email notifications with configurable address
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: How should this be built? What patterns to follow? What files to create/modify?
      placeholder: |
        **New files:**
        - `modules/monitoring-alerts.bicep`
        
        **Modify:**
        - `main.bicep` - Add module reference
        - `README.md` - Add documentation
        
        **Follow patterns in:**
        - `modules/app-service.bicep` for naming conventions
    validations:
      required: true

  - type: textarea
    id: standards
    attributes:
      label: Standards & Constraints
      description: What conventions, regions, tags, or constraints apply?
      placeholder: |
        - Region: swedencentral
        - Tags: Environment, ManagedBy, Project, Owner
        - Follow CAF naming conventions
        - Do NOT modify existing alert rules
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we verify success? Use checkboxes.
      placeholder: |
        - [ ] `bicep build main.bicep` succeeds
        - [ ] All alert rules created
        - [ ] Action group configured
        - [ ] README updated
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex is this task?
      options:
        - Low (single file, simple change)
        - Medium (multiple files, moderate logic)
        - High (many files, complex dependencies)
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Task Type
      description: What kind of task is this?
      options:
        - Add new module/feature
        - Modify existing code
        - Documentation
        - Refactoring
        - Bug fix
        - Configuration change
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Verify your issue is ready for Copilot
      options:
        - label: I've specified the exact file paths involved
          required: true
        - label: I've included specific requirements (not vague)
          required: true
        - label: I've defined acceptance criteria
          required: true
        - label: This is a single, scoped task (not multiple unrelated changes)
          required: true
