name: New Scenario Request
description: Propose a new demo scenario for the Agentic InfraOps repository
title: "[Scenario]: "
labels: ["scenario", "enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 New Scenario Request

        Propose a new demo scenario that showcases Agentic InfraOps capabilities.
        Good scenarios demonstrate real-world Azure infrastructure patterns that
        benefit from AI-assisted development.

  - type: input
    id: scenario-name
    attributes:
      label: Scenario Name
      description: A short, descriptive name for the scenario
      placeholder: "E.g., Multi-region E-commerce Platform"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Scenario Description
      description: Describe the scenario and what it demonstrates
      placeholder: |
        This scenario demonstrates building a multi-region e-commerce platform with:
        - Azure Front Door for global load balancing
        - Azure SQL with geo-replication
        - Azure Cache for Redis
        - Azure Functions for order processing
    validations:
      required: true

  - type: dropdown
    id: target-audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this scenario?
      options:
        - IT Pros learning Azure/IaC
        - System Integrator (SI) partners
        - Enterprise architects
        - Developers
        - All audiences
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity Level
      description: How complex is this scenario?
      options:
        - Beginner (15-30 min, 3-5 resources)
        - Intermediate (30-60 min, 5-10 resources)
        - Advanced (60+ min, 10+ resources)
    validations:
      required: true

  - type: textarea
    id: azure-services
    attributes:
      label: Azure Services Involved
      description: List the Azure services this scenario will use
      placeholder: |
        - Azure App Service
        - Azure SQL Database
        - Azure Key Vault
        - Azure Front Door
        - Azure Monitor
        - Azure Private Link
    validations:
      required: true

  - type: textarea
    id: waf-pillars
    attributes:
      label: Well-Architected Framework Focus
      description: Which WAF pillars does this scenario emphasize?
      placeholder: |
        **Primary focus:**
        - Reliability (multi-region, failover)
        - Security (private endpoints, managed identity)

        **Secondary:**
        - Performance Efficiency (caching, CDN)
        - Cost Optimization (auto-scaling)
    validations:
      required: true

  - type: textarea
    id: learning-objectives
    attributes:
      label: Learning Objectives
      description: What will users learn from this scenario?
      placeholder: |
        After completing this scenario, users will understand:
        1. How to design multi-region architectures
        2. How to implement global load balancing with Azure Front Door
        3. How to configure geo-replication for Azure SQL
        4. Best practices for session management with Redis Cache
    validations:
      required: true

  - type: textarea
    id: existing-scenarios
    attributes:
      label: Comparison to Existing Scenarios
      description: How is this different from existing scenarios in the repository?
      placeholder: |
        Unlike S01 (basic web app), this scenario:
        - Spans multiple regions
        - Includes global load balancing
        - Demonstrates active-active patterns
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: Expected Deliverables
      description: What should be produced for this scenario?
      placeholder: |
        - [ ] README.md with overview and prerequisites
        - [ ] DEMO-SCRIPT.md with step-by-step instructions
        - [ ] Bicep templates in `infra/bicep/` folder
        - [ ] Architecture diagram (Python diagrams-as-code)
        - [ ] Cost estimate document
        - [ ] Prompt examples for each agent
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I've reviewed existing scenarios to avoid duplication
          required: true
        - label: This scenario demonstrates a real-world use case
          required: true
        - label: The scenario can be completed in a reasonable demo timeframe
          required: true
        - label: The Azure services used are generally available (not preview)
          required: false
